# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_ninjas', '0002_ninja_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='made a blanket description statement'),
            preserve_default=False,
        ),
    ]
